### ISSUE TITLE
Getting white screen after photo deletion

### ISSUE THREAD

**Issue by janmarsicek** [rossumai/elis-capture#6]
**Steps to reproduce:**
1. Take multiple photos
2. Enter the preview mode
3. Delete the last photo
4. Swipe left
5. User is stuck at the white screen (see the pic below)

![IMG_0570](https://user-images.githubusercontent.com/3601311/55550937-ddc3cf00-56d9-11e9-80c7-b232365dfd6d.PNG)

**Expected behavior:**
Camera view should be initiated and user should be able to take another photo

**Comment by janmarsicek** [comment]
Seems there are also other problems with swipe navigation after photo deletion

**Comment by EskelCz** [comment]
It's caused by internal bugs of react-native-swiper. There are many open issues about it:
https://github.com/leecade/react-native-swiper/issues/906
https://github.com/leecade/react-native-swiper/issues/649
https://github.com/leecade/react-native-swiper/pull/646
https://github.com/leecade/react-native-swiper/issues/538
https://github.com/leecade/react-native-swiper/issues/163
https://github.com/leecade/react-native-swiper/issues/82
https://github.com/leecade/react-native-swiper/issues/20

I see three approaches to fixing it:
1. Fixing the internal bug. There is a PR which attempts to do this, maybe it does, need to check:
https://github.com/leecade/react-native-swiper/pull/646
2. Force Swiper rerender when the number of pages should change. I've tested it and it works well. I will open a PR with the change.
3. Try a different viewpager library. I have a good experience with React-Native-ViewPager, but not with changing number of pages in runtime.

**Comment by zepod** [comment]
@EskelCz thank you! Research well done and the fix is slick.
